# Generated by Django 5.2.7 on 2026-02-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollment_admin_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='registration_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
